/*******************************************************************************
 * DEMO PROJECT: Global Marathon Analytics - Snowflake Intelligence Demo
 * Script: Database and Schema Creation
 * 
 * ⚠️  NOT FOR PRODUCTION USE - EXAMPLE IMPLEMENTATION ONLY
 * 
 * PURPOSE:
 *   Creates database, schemas, and role for the demo environment
 * 
 * CREATES:
 *   - Database: SNOWFLAKE_EXAMPLE
 *   - Schemas: RAW_INGESTION, STAGING, ANALYTICS
 *   - Role: SFE_MARATHON_ROLE
 * 
 * PREREQUISITES:
 *   - ACCOUNTADMIN role (or CREATE DATABASE privilege)
 * 
 * IDEMPOTENT: Yes (safe to re-run)
 ******************************************************************************/

USE ROLE ACCOUNTADMIN;

-- Create database (preserves if exists)
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_EXAMPLE
  COMMENT = 'DEMO: Global Marathon Analytics - NOT FOR PRODUCTION';

USE DATABASE SNOWFLAKE_EXAMPLE;

-- Create RAW_INGESTION schema
CREATE SCHEMA IF NOT EXISTS RAW_INGESTION
  COMMENT = 'DEMO: Landing zone for raw data';

-- Create STAGING schema
CREATE SCHEMA IF NOT EXISTS STAGING
  COMMENT = 'DEMO: Cleaned and standardized data';

-- Create ANALYTICS schema
CREATE SCHEMA IF NOT EXISTS ANALYTICS
  COMMENT = 'DEMO: Analytics-ready tables and semantic views';

-- Create demo role
CREATE ROLE IF NOT EXISTS SFE_MARATHON_ROLE
  COMMENT = 'DEMO: Role for marathon analytics demo users';

-- Grant database and schema privileges
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE SFE_MARATHON_ROLE;
GRANT USAGE ON SCHEMA RAW_INGESTION TO ROLE SFE_MARATHON_ROLE;
GRANT USAGE ON SCHEMA STAGING TO ROLE SFE_MARATHON_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE SFE_MARATHON_ROLE;

-- Grant future privileges on tables and views
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_INGESTION TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RAW_INGESTION TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA STAGING TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE SFE_MARATHON_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_INGESTION TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_INGESTION TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STAGING TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE SFE_MARATHON_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS TO ROLE SFE_MARATHON_ROLE;

-- Grant the role to ACCOUNTADMIN for demo convenience
GRANT ROLE SFE_MARATHON_ROLE TO ROLE ACCOUNTADMIN;

/*******************************************************************************
 * END OF SCRIPT
 ******************************************************************************/
